### ISSUE TITLE
More info please?

### ISSUE THREAD

**Issue by saifulss** [GovTechSG/apex-proxy-node#13]
Hi,

Senior Systems Analyst here from PUB. I lead up a small in-house software engineering team here in PUB.

We're POCing a solution architecture that involves APEX. API bridging scenario. We're bridging a REST API that's hosted on our intranet, to expose it to the internet as endpoints protected by L2.

Working with L2 APEX requires us to attach headers whose value is generated using some secrets - naturally, we cannot allow client devices to call our L2 endpoints directly.

Which naturally leads us to this - the need for a proxy box to receive requests from the client devices, attach the headers and send them along to the L2 endpoints on internet APEX.

Phew.

So anyway, we've been trying a few things to no avail - including rolling up our own NodeJS app. When I figured what if our good friends at GDS already posted something on GitHub?

One hail mary long shot later, here I am! This repo looks like exactly what I'm looking for.

Can I trouble you to elaborate the readme.md to describe how one might be able to use this repo, please?

**Comment by ryanoolala** [comment]
hi @saifulss I've added description on the environment variables for your information.

I will continue to work on the instructions, meanwhile do let us know if you have any priority questions :)
 
Cheers

**Comment by saifulss** [comment]
@ryanoolala thanks mate.

We're currently trying to go at it using the node-apex-api-security npm package on our own NodeJS app rolled out just for this testing, whilst waiting on your reply on this thread.

We're at the point where we're testing the L1 intranet APEX endpoint using the npm package aforementioned. Unfortunately, it's not working. Can't figure out whether the error is in our configuration of the APEX stuff or our use of the npm package.

Thing is, with L1 on, testing the intranet API endpoint using the APEX test client works. So that means APEX should be fine. 

Note that L0 (i.e. no security policy attached) worked fine - our intranet Postman could hit the endpoint and get the correct data response.

Sigh. I wish the APEX documentation was a lot clearer.

**Comment by ryanoolala** [comment]
I've faced a fare amount of blocks in my adventure with it thus far too.

To confirm, you are able to reach APEX right?
you can check if you are reaching APEX using the monitor -> logs, if you're getting a 401, you should then check the values you are configuring to get your signature from node-apex-api-security. 

It is quite confusing, but most errors i faced is due to misunderstanding of the library's configuration. 
E.g the urlPath value has to include .e.api for external and .i.api for internal. Even though your target url is .api, the signing algorithm uses the .e.api string value

**Comment by robincher** [comment]
Hi Saiful,

Perhaps you can raise an issue in the library repository directly, and my team will look into that.  If possible, please provide us how you construct the Authorization header and its corresponding params.

Thanks @ryanoolala for looking into that too. The e and i thing was due to legacy network design, and we are aiming to get ride of it in the near future. 

_Sigh. I wish the APEX documentation was a lot clearer._
Yes it is not the most straight forward to use. 
Always welcome feedback, do tell us how we can improve on this aspect :) .

**Comment by saifulss** [comment]
@ryanoolala exactly! The whole .e and .i thing threw us on a loop for a good 3 days! I kept getting SSL errors and how the cert is cleared for *.api.gov.sg but I'm trying to hit pub.e.api.gov.sg and I'm like goddamn you machine isn't that what a wildcard is supposed to do just swallow it already, only to realize DNS takes a different definition of "wildcard" - but not before I spent sleepless nights watching videos on PKI and root certificates and wondering if I'm using the 4 certs provided by the APEX portal all wrong and just generally doubting my own abilities and contemplating shaving my head, finding a cave in Nepal and be a monk instead.

I still cry myself to sleep, wake up randomly screaming, "Hostname/IP does not match certificate's altnames!!!".

**Comment by saifulss** [comment]
@robincher good on you mate for popping on. I appreciate it. Hope you didn't take my lamentation as a slight, not here to bust balls.

I already intend to submit a pull request with edits to the readme of that NodeJS repo, with perspective from an agency dev trying to use it. I know it's hard to "get" a user's perspective for the product you've been building for so long and know inside out.

Maybe even post my first Medium article about it too.

**Comment by saifulss** [comment]
@robincher I've also reached out to one Timothy Loh and one Tony Singh from the APEX team. Going over to Hive to meet them this coming Mon 2pm, camp out there with our dev and WOG machines and basically just squat there till we get this thing sorted.

Lots of things to clarify. And perhaps share with you guys how it can be confusing for an agency dev trying to onboard with APEX.

If you're available, catch me then.

**Comment by robincher** [comment]
Hi @saifulss 

There are a few things for certificates, a) one for signing the HTTP Signature (L2) and b) another for establishing a TLS connection between your client and APEX.

 _"Hostname/IP does not match certificate's altnames!!!"._

Hope this is already solved? This issue seems to be not trusting the root ca within the server?

I leave the consultation to Tony and Tim, and hopefully we get it resolved for you and gradually improve our documentation.

Yeah, see you on Monday, i be sitting around Tony / Timothy desk can come over say hi :)

**Comment by robincher** [comment]
Hi @ryanoolala  think we can close this issue , our team will take it from there :)
