### ISSUE TITLE
Unclear on significance of GATEWAY_2_xxx values

### ISSUE THREAD

**Issue by saifulss** [GovTechSG/apex-proxy-node#16]
Trying to get this up and running.

Copied .env-example to .env, saw some entries there. Cool.

Went to docker-compose.yml - saw some of the same entries repeated there. Hmm OK.

* Which one is the winner? The value in the .env or the value in the docker-compose.yml?

* In my API bridging use case, I only have 1 Apex-internet gateway and 1 Apex-intranet gateway. I don't have 2 Apex-internet gateways. I'll be using this apex-proxy-node on the internet side of things, receiving requests from clients and proxying them over to my 1 Apex-internet gateway. What do the slew of GATEWAY_2_xxx values refer to?

**Comment by ryanoolala** [comment]
Hi saiful,

the .env is used in the event you want to start the application on your local machine. When using docker compose, the values in docker compose take place instead of the ones in .env

You have 2 gateways here, your first is a INTERNAL intranet gateway, second is your EXTERNAL internet gateway

**Comment by saifulss** [comment]
Just to confirm, "first" and "second" depends on perspective right?

E.g. my consumer is inter and the producer counterpart is intra, so that means "gateway 1" is internet gateway whilst "gateway 2" is intranet gateway.

Had it been such that my consumer is in intra, then "gateway 1" is the intranet gateway. But this scenario makes having a standalone proxy (like this NodeJS proxy I'm building) a little meaningless cos I already have control over an app box in my intranet - can just plonk the secrets in there, no need for a proxy box.

**Comment by ryanoolala** [comment]
Yes you are right, think from the perspective of a request, the gateway 1 is just the first gateway it passes through, regardless of internet or intranet, therefore specifying internal or external variables to the respective gateways is important in allowing the right header keys to be used. So it works both directions.

The architecture of my project is more distributed in nature, so this allows me to not create and insert multiple secrets to my applications, and our developers do not have to be concerned about the existence of APEX in their codebase, as well as infrastructure design. Although it is important to bare in mind sharing we should not share APEX application across services that you do not own, as you will want to individually create an app for each client so that you can still revoke access individually.

In the scenario that you will only have 1 code base to manage and deploy,  this apex-proxy may not add any significant value in your design.

**Comment by saifulss** [comment]
I think I get what you mean. Further testing needed on my part.

Thanks for the assist. Can close this issue for now.

**Comment by ryanoolala** [comment]
cheers
